version: '3.5'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    volumes:
      - ./data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xmx512m -Xms512m"
      - XX:ParallelGCThreads=N
      - discovery.type=single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.0
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
      -
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.15
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node
  oap:
    image: apache/skywalking-oap-server:8.4.0-es6
    depends_on:
      - elasticsearch
    ports:
      - 11800:11800
      - 12800:12800
    environment:
      SW_STORAGE: elasticsearch
      SW_STORAGE_ES_CLUSTER_NODES: elasticsearch:9200
      SW_HEALTH_CHECKER: default
      SW_TELEMETRY: prometheus
    healthcheck:
      test: ["CMD", "./bin/swctl", "ch"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  ui:
    image: apache/skywalking-ui:8.4.0
    depends_on:
      - oap
    ports:
      - 28080:8080
    environment:
      SW_OAP_ADDRESS: oap:12800